blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {malik4041} and {https://github.com/malik4041/VihangaBot-MD-V3} for your environment
    url: https://github.com/malik4041/ToDo/issues/new?template=custom.md&projects=malik4041%2FToDo%2F1&labels=ToDo
